### ISSUE TITLE
Implement Lock teams button and functionality

### ISSUE THREAD

**Issue by seanhorgan98** [seanhorgan98/fantasyhockey#42]

**Comment by SamOwenH** [comment]
Each team has a var for transferSetting:
0 - during gameweek
1- transfers enabled
2 - unlimitted transfers - between team creation and start of first week + christmas?

**Comment by SamOwenH** [comment]
Just need button to loop through and set values. Can't finish until team creation sorted

**Comment by SamOwenH** [comment]
Job donezo
