### ISSUE TITLE
Mod ability to create games

### ISSUE THREAD

**Issue by SamOwenH** [seanhorgan98/fantasyhockey#57]
Don't know how to structure data in this

Main problem with this will be keeping data integrity - need to update everywher.

Do we need records of the games? Or is just updating player stats enough?
Fixtures and Results looking like a future feature / patch atm

**Comment by SamOwenH** [comment]
@seanhorgan98

**Comment by seanhorgan98** [comment]
Think we should have a Collection for games as well as just updating all data so we can look at individual games later on.

**Comment by SamOwenH** [comment]
Creating games is now Possible
Games created with unique ID's, list of involved players and opponent fields

Remaining task is adding data to these players

**Comment by SamOwenH** [comment]
This is now fully handled and as far as I know, reliable. 
Will walk you through process in glasgow
