### ISSUE TITLE
MyTeam throwing "method called on null" error because it tries to load the team before it knows which team it is trying to load.

### ISSUE THREAD

**Issue by seanhorgan98** [seanhorgan98/fantasyhockey#59]
Need to somehow set an initial team to load while it waits for the actual data from firestore.

**Comment by SamOwenH** [comment]
When breakpoint-ing through it says that it gets the user collection instead of the teams collection when it bugs.
Maybe make a loading screen the default and when the snap.exists is true change to the proper layout?

**Comment by SamOwenH** [comment]
Pushed fix.
Issue was you didn't use setState to update the state correctly in the init method

**Comment by SamOwenH** [comment]
Fixed with while loop
