### ISSUE TITLE
League Standings for GUMHC teams

### ISSUE THREAD

**Issue by seanhorgan98** [seanhorgan98/fantasyhockey#7]
Showing the league tables for our 3 teams in Scottish Hockey. eg. West 1A and West 1B

**Comment by seanhorgan98** [comment]
The thought of trying to web crawl Scottish Hockey's website is giving me nightmares. Might have to forgo this idea unless its easier than i think.

**Comment by SamOwenH** [comment]
Yeah would give this a serious patch
